services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: base_api_db

    ports:
      - 5431:5432

    volumes:
      - pgdata:/var/lib/postgresql


  maildev:
    image: maildev/maildev
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_WEB_PORT=1080
    ports:
      - 8080:1080
      - 1025:1025

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    


volumes:
  pgdata: